[package]
name = "parquet-datafusion"
version = "0.1.0"
authors = ["nick <nick.hortovanyi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "^0.16.0"
parquet = "^0.16.0"
datafusion = "^0.16.0"